### ISSUE TITLE
Add support for ChefSpec / Chef Cookbooks

### ISSUE THREAD

**Issue by ephracis** [codeclimate/ruby-test-reporter#113]
I am testing the ruby code in my Chef cookbooks using [ChefSpec](http://sethvargo.github.io/chefspec/) and it has the ability to [report code coverage](https://sethvargo.com/chef-recipe-code-coverage). When I run the `ruby-test-reporter` it doesn't find any code and thus errors with `CodeClimate::TestReporter::InvalidPayload`. 

It would be awesome if support for testing Chef cookbooks was added so I could get proper coverage included in my CodeClimate reports.

**Comment by pbrisbin** [comment]
Hi @ephracis, that does sound like a useful feature. Unfortunately, I don't think we can commit to any kind of timeline for implementing it right now. I'd be happy to review any Pull Requests in that area though.

**Comment by ephracis** [comment]
Looking at SimpleCov it doesn't seem like a good fit to add the support there. Perhaps the best approach would be to abstract away SimpleCov as a backend/plugin, add ChefSpec as a second backend/plugin and then allow the user to specify which backend/plugin to use, defaulting to SimpleCov.

This would keep backwards compatibility while extending the tool with support for additional coverage engines.

**Comment by dblandin** [comment]
Hey @ephracis ,

Thank for the issue!

As we're winding down development on this ruby-specific reporter, I'd recommend checking out our new test reporter and migrating to it if you're interested!
https://github.com/codeclimate/test-reporter
https://codeclimate.com/changelog/591c99570d51f6481f001291

It's decoupled from the coverage tool used to generate the report, distributed as a static binary, and has support for parallelized builds. 🎉 

Looks like the test coverage report format for ChefSpec might not output in a standarized format, but we've architected the new test reporter so that it's easy to support additional formats. Let me know if you'd like to discuss that further!
