### ISSUE TITLE
Suggestion: Automatically run reporter

### ISSUE THREAD

**Issue by dueckes** [codeclimate/ruby-test-reporter#144]
Gem version: 1.0.1

**Premise**
It would be simpler for Code Climate customers to have the reporter automatically run when the CODECLIMATE_REPO_TOKEN is present.

If necessary customers could have the ability to explicitly disable the reporter, rather than explicitly enable the reporter.

**Comment by dblandin** [comment]
Hi @dueckes,

This was how our ruby test reporter used to work, by injecting our reporting into SimpleCov's test coverage process.

We take the separately invoked binary approach for [all of](https://github.com/codeclimate/python-test-reporter) [our other](https://github.com/codeclimate/php-test-reporter) [test reporters](https://github.com/codeclimate/javascript-test-reporter), so there are some consistency points gained by extracting the reporting process. However, the primary reason for making this change is to fix a reporting bug present in earlier versions: the reporter would send reports to codeclimate.com even when the CI build failed, sometimes with partial data when the test suite is configured to fail fast.

This led to confusing behavior on codeclimate.com and on GitHub repo pages displaying the test coverage badge. The "covered" percent for the project would flip between the correct value and a seemingly random incorrect value. Since many test suites are randomized, how far a fail fast test suite made it before failing would determine the incorrect covered percent.

Given this problem and our internal roadmap for test coverage reporting, this approach makes the most sense to us.

Hope that all makes sense! Let me know if you have any further questions.

**Comment by dueckes** [comment]
Thanks @dblandin 

If there is an appetite for automatically running the reporter at some stage, it sounds like running the reporter only when tests succeed is appropriate.

Happy for you to close this as it sounds like you've already given this suggestion good thought.

**Comment by awendt** [comment]
@dblandin Thanks for explaining all this!

**Comment by pbrisbin** [comment]
Thanks for bringing this up @dueckes, going ahead with closing.
