### ISSUE TITLE
UPGRADE simplecov dependency

### ISSUE THREAD

**Issue by anthony-robin** [codeclimate/ruby-test-reporter#187]
Simplecov is currently locked to `<= 0.13` whereas the actual version is `0.14.1`.
Could you unlock or update this dependency version ?

**Comment by pbrisbin** [comment]
Hi @anthony-robin, I apologize but we're unable to use `0.14` because we rely on some internals that are changed in that version. https://github.com/codeclimate/ruby-test-reporter/issues/180 has more details.

You should check out our new language-agnostic [test-reporter](https://github.com/codeclimate/test-reporter). It's currently in its early stages, but we're looking for some early adopters to try it out.
