### ISSUE TITLE
Update to latest simplecov

### ISSUE THREAD

**Issue by mfdavid** [codeclimate/ruby-test-reporter#188]
Right now ruby-test-reporter is requesting simplecov <= 0.13.

Any special reason for not accepting the latest version?

**Comment by maxjacobson** [comment]
Hi @mfdavid,  I apologize but we're unable to use `0.14` because we rely on some internals that are changed in that version. https://github.com/codeclimate/ruby-test-reporter/issues/180 has more details.

You should check out our new language-agnostic [test-reporter](https://github.com/codeclimate/test-reporter). It's currently in its early stages, but we're looking for some early adopters to try it out. You should be able to use a newer simplecov to generate your coverage data and then the new test-reporter to report it to Code Climate.

**Comment by ylecuyer** [comment]
@maxjacobson you want us to use the new test-reporter but documentation is the worst

**Comment by maxjacobson** [comment]
@ylecuyer Hi Yoann. Sorry to hear you're having difficulty setting up the new test-reporter. We have [this doc](https://docs.codeclimate.com/docs/setting-up-test-coverage) which includes a section on troubleshooting. If that doesn't clear it up, you've probably identified a gap in our docs that we'd appreciate more info about so we can fill it in. Do you mind elaborating on where you got stuck, either here or via [a support request](https://codeclimate.com/help) so we can help you out?
