### ISSUE TITLE
Intermittent: Code Climate encountered an exception: RuntimeError in post_results

### ISSUE THREAD

**Issue by loren** [codeclimate/ruby-test-reporter#28]
This is happening some of the time via TravisCI:

Coverage = 100.0%. Sending report to https://codeclimate.com for branch master... Code Climate encountered an exception: RuntimeError
HTTP Error: 500
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/codeclimate-test-reporter-0.2.0/lib/code_climate/test_reporter/client.rb:64:in `post_results'
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/codeclimate-test-reporter-0.2.0/lib/code_climate/test_reporter/formatter.rb:23:in`format'
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/simplecov-0.8.2/lib/simplecov/result.rb:46:in `format!'
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/simplecov-0.8.2/lib/simplecov/configuration.rb:139:in`block in at_exit'
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in `call'
/home/travis/.rvm/gems/ruby-2.0.0-p353/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in`block in <top (required)>'

**Comment by lelea2** [comment]
We are using Jenkins for build, Rails 5 -api, ruby 2.3.x
Try to run both
CODECLIMATE_REPO_TOKEN=your_repo_token bundle exec rspec
CODECLIMATE_REPO_TOKEN=your_repo_token bundle exec codeclimate-test-reporter (after rspec), both solution doesn't seem working.

**Comment by maxjacobson** [comment]
@lelea2 hi Khanh, sorry to hear that. Do you mind writing in to our support team at https://codeclimate.com/help with some more information about your Jenkins configuration? The reporter needs to be able to look up some information from the environment, and because Jenkins is so configurable, it doesn't always work without a little setup. We're happy to help!
