### ISSUE TITLE
Is CODECLIMATE_REPO_TOKEN a secret?

### ISSUE THREAD

**Issue by jimmycuadra** [codeclimate/ruby-test-reporter#34]
Should the value of CODECLIMATE_REPO_TOKEN be encrypted when checked into a .travis.yml on an open source project or is it a public key? I'm not entirely clear what the purpose of this token is. I'm probably not the only one wondering, so it might be useful to clarify this in the project README and the documentation on the Code Climate website.

**Comment by jonathancadepowers** [comment]
I'm closing this one out, as we now have a help doc on this issue: http://docs.codeclimate.com/article/276-should-i-keep-my-test-coverage-token-secret

**Comment by XedinUnknown** [comment]
The doc returns a 404.

**Comment by jakeasmith** [comment]
Did this move again? I'm not immediately seeing a direct answer to this.

**Comment by davehenton** [comment]
Hey @jakeasmith -- sorry for the confusion here. This information is now found at the bottom of [this page](https://docs.codeclimate.com/docs/finding-your-test-coverage-token#section-should-i-keep-my-test-reporter-id-secret). Let me know if you have any further questions. Happy to help.

**Comment by jakeasmith** [comment]
Aha! Thank you for the prompt response! Cheers.

**Comment by pimousse1099** [comment]
@davehenton sorry for reopening the conversation but I'm wondering what happens if a user uses a `repo_token` that is related to the wrong repo 🙂

Is the test coverage gonna be updated with the results ?

even worse, let's say a user forked a repo `A` to a repo `B` that has the token in its `.travisCI.yaml`
if the user adds repo `B` on its travisCI, eventually, the test results will be sent to codeClimate with the wrong repo_token (repo `A`token) ... am I right ?

--

A workaround for this is to set the `CC_TEST_REPORTER_ID` as a [build env variable directly in the CI](https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings) and then use the env var in the after script.

> Note: I don't know why, but the build env var does not seem to be setted in the after_script travis stage

```
after_script:
  - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
```

another way can be to [encrypt the token and add it to env.global .travisCI.yam](https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables)

```
travis encrypt CC_TEST_REPORTER_ID=<super_code_climate_token> --add env.global
```

I hope this can help 👍
