### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by tielur** [codeclimate/ruby-test-reporter#38]
I'm currently getting this issue when running tests. We use capistrano to deploy our code and we are using these settings:

`set :deploy_via, :copy`
`set :copy_strategy, :export`

Which allows us to push our code to our web servers without needing them to connect to our git servers and pull code. It basically does a sftp. [more info](http://bu.chsta.be/blog/2013-02-24/capistrano-deployment-strategies-deploy-via-a-copy/)

Unfortunately this means that there is not a git repository at the time the tests are run. Which it looks like the [Formatter.to_payload](https://github.com/codeclimate/ruby-test-reporter/blob/master/lib/code_climate/test_reporter/formatter.rb#L68) uses as well as the [PayloadValidator](https://github.com/codeclimate/ruby-test-reporter/blob/master/lib/code_climate/test_reporter/payload_validator.rb)

I guess my question is does CodeClimate need this git repo information in order to function correctly? If not, how should we go about fixing this so it's not required to be run inside a git repository.

Also, is anyone else using this capistrano deploy method? 

Logs:

```
Coverage = 69.48%. fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
A git commit timestamp was not found in the test report payload
/jenkins-test/shared/bundle/ruby/2.0.0/gems/codeclimate-test-reporter-0.3.0/lib/code_climate/test_reporter/payload_validator.rb:16:in `validate'
/jenkins-test/shared/bundle/ruby/2.0.0/gems/codeclimate-test-reporter-0.3.0/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
/jenkins-test/shared/bundle/ruby/2.0.0/gems/codeclimate-test-reporter-0.3.0/lib/code_climate/test_reporter/formatter.rb:17:in `format'
/jenkins-test/shared/bundle/ruby/2.0.0/gems/simplecov-0.8.2/lib/simplecov/result.rb:46:in `format!'
/jenkins-test/shared/bundle/ruby/2.0.0/gems/simplecov-0.8.2/lib/simplecov/configuration.rb:139:in `block in at_exit'
/jenkins-test/shared/bundle/ruby/2.0.0/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in `call'
/jenkins-test/shared/bundle/ruby/2.0.0/gems/simplecov-0.8.2/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

**Comment by NullVoxPopuli** [comment]
I'm receiving a similar error in my gem NullVoxPopuli/authorizable

    Coverage = 84.31%. fatal: Not a git repository: '/home/me/Development/authorizable/spec/support/rails_app/.git'
    fatal: Not a git repository: '/home/me/Development/authorizable/spec/support/rails_app/.git'
    fatal: Not a git repository: '/home/me/Development/authorizable/spec/support/rails_app/.git'
    Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
    A git commit timestamp was not found in the test report payload
    /home/me/.rvm/gems/ruby-2.1.5/gems/codeclimate-test-reporter-0.4.4/lib/code_climate/test_reporter/payload_validator.rb:16:in `validate'
    /home/me/.rvm/gems/ruby-2.1.5/gems/codeclimate-test-reporter-0.4.4/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
    /home/me/.rvm/gems/ruby-2.1.5/gems/codeclimate-test-reporter-0.4.4/lib/code_climate/test_reporter/formatter.rb:21:in `format'
    /home/me/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/result.rb:46:in `format!'
    /home/me/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/configuration.rb:158:in `block in at_exit'
    /home/me/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `call'
    /home/me/.rvm/gems/ruby-2.1.5/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `block in <top (required)>'

**Comment by dukedave** [comment]
Not sure whether to open a new issue or request a re-open?

We're also seeing this (on 0.4.5), but for a slightly different reason:
Since switching to [use Codeship's Docker support](http://pages.codeship.com/docker) we no longer have `.git` available during our CI builds ([per Step 4 in their docs](https://blog.codeship.com/running-rails-development-environment-docker/)).

I'm a little confused, because:

1. The docs aren't explicit that a `.git` is required ¹, and:
1. In [at least one place](https://github.com/codeclimate/ruby-test-reporter/blob/v0.4.5/lib/code_climate/test_reporter/git.rb#L14) the codes alludes to preferring information from CI and failing over to git, however it doesn't seem to be consistent. I opened #115 for a specific instance of this.

For the sake of this issue, I suppose a good start would be a clarification in the docs that a `.git` is expected. Then perhaps you could look to providing official support for running without git (by extracting all necessary information from CI environmental variables)?

****

¹ although [the docs do allude to its existence](https://github.com/codeclimate/ruby-test-reporter/tree/v0.4.5#configuration), stating:
> when your Rails application root is not at the root of the git repository root
